### PR TITLE
Handle whitespace before/after newlines.

### PR DESCRIPTION
**Pull request by timlesallen**
The following will not break into two separate paragraphs at present:
```
'I am a fish.  \n \n  I am a horse.'
```
This makes is so they do.

### CODE REVIEW

**Comment by wooorm** [comment]
Thanks Tim! Looks good, and the tests as well. Anything you'd like to add about this / points of consideration in general?

**Comment by timlesallen** [comment]
Not really @wooorm.  I guess  just to give a little context as to the why...
We are using this as part a slide splitting algorithm.  One option we offer is 'split by paragraph' and this works as long as users perfect execute their paragraphing.... But they don't always!  So this helps with that.  Love your work, found the ecosystem nice to work with :)

**Comment by wooorm** [comment]
Cool to hear!

Hey, do you think this is a major or minor release?

**Comment by timlesallen** [comment]
@wooorm Personally I'd say this is a minor release as I can't really think of too many situations where you would be 'reliant' on the old behaviour (i.e. whitespace causes breaking to not occur.)  Hence, according to the strict definition of a 'breaking' change, I would not think it should break things for anyone...  What about you?

**Comment by wooorm** [comment]
Thanks a lot @timlesallen! Released in 3.2.0 in a minute!

**Pull request closed without merging**
